apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibaba-kafka-proucer
  namespace: default
  labels:
    app: alibaba-kafka-proucer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alibaba-kafka-proucer
  template:
    metadata:
      labels:
        app: alibaba-kafka-proucer
    spec:
      containers:
      - name: kalibaba-kafka-proucer
        image: registry.cn-beijing.aliyuncs.com/kafka-test/alibaba-kafka-client:latest
        env:
        - name: kafka_server
          value: "192.168.0.53:9092,192.168.0.52:9092,192.168.0.51:9092"
        - name: kafka_topic
          value: kafka-demo-test
        - name: produce_enable
          value: "true"
        - name: consume_enable
          value: "false"

